### ISSUE TITLE
PSR-4 Compatibility

### ISSUE THREAD

**Issue by browner12** [sebastianbergmann/money#50]
I would like to update this package to be PSR-4 compatible. What this entails would be

+ a couple of namespace changes for files in the `currency`, `exceptions`, and `interfaces` directories.
+ update the currency template file
+ update `composer.json` to autoload via PSR-4
+ update `src` files to reflect new namespaces
+ update `readme` to reflect new namespaces

Since this would be a little more time consuming that my previous PRs, I wanted to get your feedback on it first, and if it would be a welcome commit.

**Comment by sebastianbergmann** [comment]
Sorry, but no.
