### ISSUE TITLE
Minor Release

### ISSUE THREAD

**Issue by browner12** [sebastianbergmann/money#58]
I submitted a PR a couple weeks ago to retrieve the value of the Money object in its base units (`getConvertedAmount`).  You accepted the PR and merged it into master. I see your eyes are on a big refactor for a 2.0 release, but is there an chance your could release this as a minor release?

**Comment by sebastianbergmann** [comment]
Makes sense. Will try to make time for this.

**Comment by jromero86** [comment]
Please, we needed! :)

**Comment by sebastianbergmann** [comment]
Done.
