### ISSUE TITLE
New method to convert negative to positive (absolute value)

### ISSUE THREAD

**Issue by samvaughton** [sebastianbergmann/money#59]
I've come across the need to convert a negative into a positive (getting the absolute value). Would you be open to accept a PR implementing a method similar to `negate()`. Maybe calling it `absolute()`?

It would most likely call this function http://php.net/manual/en/function.abs.php

On the same note, if a negative money object has `negate()` called on it, then it will turn positive. Is this the intended functionality? As it seems a bit confusing and could lead to bugs.

**Comment by clphillips** [comment]
Seems like this would suffice:

```php
$abs = $money->getAmount() > 0 ? $money : $money->negate();
```

**Comment by samvaughton** [comment]
If you are repeating that logic across a code base then it makes sense to abstract it into an `absolute()` function, don't you agree? This is what I have done, but it would be better to include it within the library itself.

**Comment by alsar** [comment]
In my opinion this functionality is out of scope of this library.
Negation or an absolute value are basic mathematical operations. So it should be implemented in some kind of mathematical library, or you can just call `abs()`. There is no real benefit of adding those methods here.

**Comment by browner12** [comment]
yes, they are basic mathematical operations, but so are adding, subtracting, and multiplying. yet we create special methods for them because money can be a tricky value.

**Comment by alsar** [comment]
@browner12 I agree, but you have to draw a line somewhere. 
I don't think negating money is that common as adding and subtracting. Just my opinion.

**Comment by samvaughton** [comment]
I agree with @browner12, and although `negate()` is not one of the basic operations, surely its counterpart should exist or neither one of them at all?

**Comment by clphillips** [comment]
@samvaughton 

I think you may be misunderstanding the concept of negation and absolute. `negate` and `absolute` are not the inverse of each other. `negate` is the inverse of `negate`.

```
-1 = -1
-(-1) = 1
-(-(-1)) = -1
```
Absolute on the other hand:

```
|-1| = 1
|-(-1)| = 1
|-(-(-1))| = 1
```

I'm not saying I'm against it adding absolute value, but I've never had a need for it. And if you're going to argue that it should be added it, you should have a compelling reason. Not one based on a misrepresentation of negation.

**Comment by samvaughton** [comment]
@clphillips yes you are right, my mistake. However I still feel that this should be included regardless due to the library including other mathematical functions.

**Comment by clphillips** [comment]
Then how about `sqrt` for square? Or `cos` to get the cosine?

If you have a compelling reason for adding any operation, please share because I fail to see why it's necessary.

**Comment by samvaughton** [comment]
A function such as `cos` is not going to be used in money calculations (and if it is then VERY rarely) whereas retrieving the absolute value of a figure is a lot more common in monetary calculations.

**Comment by clphillips** [comment]
> whereas retrieving the absolute value of a figure is a lot more common in monetary calculations. 

Is it? Because you still haven't given a single example.

**Comment by sebastianbergmann** [comment]
I still don't see the point, sorry.
