### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by mmoreram** [sebastianbergmann/money#60]
when its expected the new version?

**Comment by sebastianbergmann** [comment]
Is just a tag of the current state needed?

**Comment by GrahamCampbell** [comment]
@sebastianbergmann Looks like you've committed the build directory here by mistake btw.

**Comment by GrahamCampbell** [comment]
https://github.com/sebastianbergmann/money/tree/master/build/tools

**Comment by mmoreram** [comment]
Yes. https://travis-ci.org/elcodi/elcodi/jobs/68190004

**Comment by sebastianbergmann** [comment]
@GrahamCampbell That is not a mistake but "the right way" to do it.

**Comment by GrahamCampbell** [comment]
I just wondered if it was intentional. :)

**Comment by GrahamCampbell** [comment]
Can we exclude the build folder from the zips then so people don't have to download all of that in composer?

**Comment by GrahamCampbell** [comment]
https://github.com/sebastianbergmann/money/pull/61

**Comment by sebastianbergmann** [comment]
@mmoreram Just out of curiosity: which of these https://github.com/sebastianbergmann/money/compare/v1.6.0...master do you need in a release?

**Comment by GrahamCampbell** [comment]
It was the change in the php version constraint to allow php 7 as shown in the link he posted. :)

**Comment by mmoreram** [comment]
https://github.com/sebastianbergmann/money/commit/4a6dadbbce943c9005bd151f1c6847eeafe9534e

Change in `composer.json`. I've removed `PHP7` from allow_failure block
