### ISSUE TITLE
Unexpected behaviour of allocateToTargets and allocateByRatios with negative amounts

### ISSUE THREAD

**Issue by hollodotme** [sebastianbergmann/money#65]
A Money object representing -0,99 EUR is not allocated to 10 targets (9x -10, 1x -9) when executing the following code:

```php
<?php

$targets = (new EUR(-99))->allocateToTargets(10);

echo "Targets: ", count($targets), "\n";
foreach ($targets as $money)
{
    echo $money->getAmount(), "\n";
}
```

Prints:

    Targets: 19
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9
    -9

This is because the `%` operation results to a negative `$remainder` that leads to an unintended amount of loops in the following for-loops.

Similar issue with `allocateByRatios`:

```php
<?php
$targets = (new EUR(-5))->allocateByRatios([3,7]);

echo "Targets: ", count($targets), "\n";
foreach ($targets as $money)
{
    echo $money->getAmount(), "\n";
}
```

Prints:

    Targets: 2
    -1
    -3

The `$remainder` gets negative, the for-loop doesn't loop.

**Comment by sebastianbergmann** [comment]
Merged manually, thanks.
