### ISSUE TITLE
tags and releases are not consistent

### ISSUE THREAD

**Issue by edvinasme** [sebastianbergmann/money#67]
If you look at releases it says latest versions is 1.3.0 https://github.com/sebastianbergmann/money/releases

Which is kind of confusing as latest tag is 1.6.1.

**Comment by sebastianbergmann** [comment]
I don't use the Releases feature of GitHub, only tags.

**Comment by edvinasme** [comment]
@sebastianbergmann  I was n't suggesting to use the releases if you don't want to, merely pointing out that it's currently a bit mis-informative. If you would cleanup the old "releases" it should show latest tags as last release. It did confuse me first to use "1.3.0" version, only some time after I've noticed that there are later tags.
