### ISSUE TITLE
Allow comparaison with two different currencies

### ISSUE THREAD

**Issue by maidmaid** [sebastianbergmann/money#72]
Hi ! 

Currently, only comparisons of the same currency works. If we compare with two different currencies, an [exception](https://github.com/sebastianbergmann/money/blob/master/src/Money.php#L407) is thrown. And compare two different currencies would be very useful. By knowing the exchange rate (for instance through [florianv/swap](https://github.com/florianv/swap) package), it is possible to implement this.

**Comment by ruudk** [comment]
I have the same issue https://github.com/sebastianbergmann/money/issues/74

**Comment by sebastianbergmann** [comment]
This is intentional. Currency conversion is outside the scope of this component.
