### ISSUE TITLE
Why does equals() throw an exception when Currency does not match?

### ISSUE THREAD

**Issue by ruudk** [sebastianbergmann/money#74]
I don't understand why `equals()` throws exceptions. If you want to compare 2 money objects, if the amount or currency is different, then the result is false, right?

```php
$money1 = new Money(1000, new Currency('EUR'));
$money2 = new Money(9999, new Currency('EUR'));
var_dump($money1->equals($money2); // returns false
```

```php
$money1 = new Money(1000, new Currency('EUR'));
$money2 = new Money(9999, new Currency('USD'));
var_dump($money1->equals($money2); // throws CurrencyMismatchException
```

It should throw exceptions when comparing with less/greaterThan but why with equals?

**Comment by ruudk** [comment]
That's also how https://github.com/mathiasverraes/money/blob/master/lib/Money/Money.php#L80 does it.

**Comment by hkdobrev** [comment]
@ruudk If the currency does not match, it doesn't mean it's a different amount or a different object. It means they are not comparable.

**Comment by ruudk** [comment]
I understand, that's why the answer should be false, because they are not equal. 100$ !== 100€

**Comment by hkdobrev** [comment]
@ruudk No, not comparable means they cannot be compared and `!==` would not make sense. Just like comparing different types in some languages.

**Comment by sebastianbergmann** [comment]
Currency conversion is outside the scope of this component.
