### ISSUE TITLE
need intl extension problem

### ISSUE THREAD

**Issue by Jaggle** [sebastianbergmann/money#78]
when I use "sebastian/money": "1.6.*" ,composer said I missed ext-intl,and when I going to get this extension on[http://pecl.php.net/package/intl](url) ,but there is no version for my php version 5.6,how should I do  next ?

**Comment by browner12** [comment]
if you have sudo privileges on the server, `ssh` in and run `sudo apt-get install php5-intl`

**Comment by Jaggle** [comment]
thanks
